In [ ]:
lista = [1,2,3,4,5]

def media(lista):
    media = sum(lista) / len(lista)
    return media

resultado = media(lista)

print(resultado)

In [2]:
# reorne os nums neaivos e positivos da lista.


def positivos_negativos(lista):
    negaitvos =[num for num in lista if num < 0]
    posi = [num for num in lista if num > 0]
    return posi, negaitvos

numeros = [10,-20,30,40,50,-3,8]    
positivos, negativos = positivos_negativos(numeros)

print(f"Positivos: {positivos}")
print(f"Negativos: {negativos}")
    


Positivos: [10, 30, 40, 50, 8]
Negativos: [-20, -3]


In [12]:
# calcule a soma dos quadrados de uma lista de numeros
lista = [30, 40, 50, 6, 8, 7]
quadrados = []
for i in lista: 
    quadrados.append(i**2)

soma = sum(quadrados)
print(soma)

5149


In [22]:
pip install pandas

  Using cached pandas-2.2.1-cp311-cp311-win_amd64.whl (11.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
import pandas as pd

In [27]:
dados = pd.read_csv('manutencao_preditiva.csv')
dados_selec = dados[['Temperatura Processo [K]', 'Velocidade Rotacao [rpm]']]

cinco_linhas = dados_selec.head(5)

matriz = cinco_linhas.values
matriz

array([[ 308.6, 1551. ],
       [ 308.7, 1408. ],
       [ 308.5, 1498. ],
       [ 308.6, 1433. ],
       [ 308.7, 1408. ]])

In [24]:
import numpy as np

In [ ]:
soma_elementos = np.sum(matriz)

print(soma_elementos)

In [28]:
min_elementos = np.min(matriz)
max_elemebtos = np.max(matriz)

print(min_elementos)
print(max_elemebtos)


308.5
1551.0


In [33]:
media1 =np.mean(matriz, axis = 0) # media pela vertical da matriz (coluna)
media2 =np.mean(matriz, axis = 1) # media pela horizontal da matriz (linha)

print(media1)
print(media2)

[ 308.62 1459.6 ]
[929.8  858.35 903.25 870.8  858.35]


In [35]:
transpor = np.transpose(matriz)

media3 = np.mean(transpor, axis = 0)
media4 = np.mean(transpor, axis = 1)

print(media3)
print(media4)

[929.8  858.35 903.25 870.8  858.35]
[ 308.62 1459.6 ]


In [42]:
dados_novos = dados[['Velocidade Rotacao [rpm]', 'Torque [Nm]']]
dados_outros = dados[['Temperatura Ar [K]', 'Torque [Nm]']]
intervalo = dados_novos.iloc[15:25]
dez_linhas  = dados_outros.head(10)

matriz1 = dez_linhas.values
matriz2 = intervalo.values

print(matriz1)
print(matriz2)

[[298.1  42.8]
 [298.2  46.3]
 [298.1  49.4]
 [298.2  39.5]
 [298.2  40. ]
 [298.1  41.9]
 [298.1  42.4]
 [298.1  40.2]
 [298.3  28.6]
 [298.5  28. ]]
[[1542.    48.4]
 [1311.    46.6]
 [1410.    45.6]
 [1306.    54.5]
 [1632.    32.5]
 [1375.    42.7]
 [1450.    44.8]
 [1581.    30.7]
 [1758.    25.7]
 [1561.    37.3]]


In [43]:
soma = sum(matriz1) + sum(matriz2)
print(soma)

[17907.9   807.9]


[929.8  858.35 903.25 870.8  858.35]
[ 308.62 1459.6 ]
